class Airlines(models.Model):
    title = models.CharField(verbose_name='Название')
    country = models.CharField(verbose_name='Страна')
    birthday = models.CharField(verbose_name='Дата основания')
    birthday_full = models.BooleanField(verbose_name='Точная дата основания?')
    death = models.DateTimeField(verbose_name='Точная дата закрытия')
    death_full = models.BooleanField(verbose_name='Точная дата закрытия?')
    fleet_size = models.IntegerField(verbose_name='Число самолётов')
    status = models.CharField(verbose_name='Состояние')
    logo = models.ImageField(verbose_name='Логотип')
    site = models.CharField(verbose_name='Адрес сайта')
    wiki = models.CharField(verbose_name='Вики-страница')
    created = models.DateTimeField(verbose_name='Создано')
    changed = models.DateTimeField(verbose_name='Изменено')
    deleted = models.DateTimeField(verbose_name='Удалено')
